### PR TITLE
Add support for displayName

### PR DESCRIPTION
**Pull request by tsueho**

### CODE REVIEW

**Comment by pablo-ruth** [comment]
I released goldap v0.7.1 with your PR included, I let you upgrade the dependency in this PR :)

**Comment by tsueho** [comment]
> Hi @tsueho, I released goldap v0.7.1 with your PR included, I let you upgrade the dependency in this PR :)

Sorry for delay, now updated.

**Comment by pablo-ruth** [comment]
> > Hi @tsueho, I released goldap v0.7.1 with your PR included, I let you upgrade the dependency in this PR :)
> 
> Sorry for delay, now updated.

No problem, thanks for your contr

**Comment by pablo-ruth** [comment]
I just released [v0.8.10]https://github.com/Ouest-France/terraform-provider-ldap/releases/tag/v0.8.10 with your PR included :)

**Pull request merged**
