### PR TITLE
feat: Allow group members and description update

### PR DESCRIPTION
**Pull request by barryib**
Resolves https://github.com/Ouest-France/terraform-provider-ldap/issues/16

Depends on https://github.com/Ouest-France/goldap/pull/6

### CODE REVIEW

**Comment by pablo-ruth** [comment]
Ok I merged your PR and release a v0.5.0 of Ouest-France/goldap.

**Comment by barryib** [comment]
> Ok I merged your PR and released a v0.5.0 of Ouest-France/goldap.

done !

**Comment by pablo-ruth** [comment]
Ok I found a bug, I missed it in the goldap review. With the provider, if I try to update group members and have no description defined, I have this error on apply:
```
error: LDAP Result Code 53 "Unwilling To Perform": 00000529: SvcErr: DSID-031A1254, problem 5003 (WILL_NOT_PERFORM), data 0
```

**Comment by pablo-ruth** [comment]
The delete request on description is not idempotent (https://github.com/Ouest-France/goldap/blob/master/group.go#L61) and we always try to delete the attribute if it is empty. And I don't know why, but ActiveDirectroy doesn't let us create an empty description attribute (https://github.com/Ouest-France/goldap/blob/master/group.go#L15).

**Comment by pablo-ruth** [comment]
> Ok I found a bug, I missed it in the goldap review. With the provider, if I try to update group members and have no description defined, I have this error on apply:
> 
> ```
> error: LDAP Result Code 53 "Unwilling To Perform": 00000529: SvcErr: DSID-031A1254, problem 5003 (WILL_NOT_PERFORM), data 0
> ```

**Comment by barryib** [comment]
Humm... I was wondering if you should always add `description` and `members` attributes even if they are empty ? Or we should check if attributes are presents before every update ?

@pablo-ruth you just closed the PR. Are you working on another approach ?

**Comment by pablo-ruth** [comment]
No my mistake for closing it... Yes I think we have to check with d.HasUpdate() in the provider for changes, and probably split the UpdateGroup (https://github.com/Ouest-France/goldap/blob/master/group.go#L56) in two functions like UpdateGroupMembers and UpdateGroupDescription... What do you think about ?

**Comment by barryib** [comment]
> No my mistake for closing it... Yes I think we have to check with d.HasUpdate() in the provider for changes, and probably split the UpdateGroup (https://github.com/Ouest-France/goldap/blob/master/group.go#L56) in two functions like UpdateGroupMembers and UpdateGroupDescription... What do you think about ?

Sounds good to me. Let me update my PR accordingly.

**Comment by barryib** [comment]
@pablo-ruth please see https://github.com/Ouest-France/goldap/pull/7

**Review by pablo-ruth — APPROVED** [review]
LGTM

**Comment by pablo-ruth** [comment]
Ok v0.5.1 of goldap with your fix is released, and your code here LGTM, I just let you update go.mod and we'll be good to merge :)

**Comment by barryib** [comment]
> Ok v0.5.1 of goldap with your fix is released, and your code here LGTM, I just let you update go.mod and we'll be good to merge :)

Just bumped the goldap version. A final review please.

**Review by pablo-ruth — APPROVED** [review]
It works like a charm! :)

**Comment by metmac** [comment]
Funny enough I had built this off in a fork at the same time. Was going to PR but y'all beat me to it. 😅 
Nice to see this being brought into the provider. Would love to help further down the road if other features are needed.

Changes to the Provider:
[terraform-provider-ldap/resource_ldap_group.go](https://github.com/metmac/terraform-provider-ldap/blob/feat/group-membership-update/ldap/resource_ldap_group.go)

Changes to the underlying library:
[goldap/group.go](https://github.com/metmac/goldap/blob/feat/group-membership-update/group.go)

**Comment by pablo-ruth** [comment]
@metmac of course yes, feel free to submit PR in the future :)

**Pull request merged**
